version: '3'

services:
  engine:
      image: vue-davao-js:latest
      build: .
      container_name: vue-davao-js
      command: npm run dev
      volumes:
        - .:/vue-davao-js
      expose:
        - "4200"
      ports:
        - "4200:4200"
      environment:
        - IN_DOCKER=1
